// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Auction struct {
	AuctionID     string    `json:"auctionID"`
	Bids          []*string `json:"bids"`
	StartDate     *string   `json:"startDate"`
	AuctionLength *string   `json:"auctionLength"`
	ServiceDesc   *string   `json:"serviceDesc"`
	Freelancer    *User     `json:"freelancer"`
}

type Bidder struct {
	Ammount  *string `json:"ammount"`
	Account  *User   `json:"account"`
	BidderID string  `json:"bidderID"`
}

type NewAuction struct {
	StartDate     *string `json:"startDate"`
	AuctionLength *string `json:"auctionLength"`
	ServiceDesc   *string `json:"serviceDesc"`
	FreelancerID  *string `json:"freelancerID"`
}

type NewUser struct {
	Name  *string `json:"name"`
	Email *string `json:"email"`
}

type User struct {
	Name         string     `json:"name"`
	UserID       string     `json:"userID"`
	Email        string     `json:"email"`
	Phone        string     `json:"phone"`
	PriorityList []*Bidder  `json:"priorityList"`
	Auctions     []*Auction `json:"auctions"`
}
